---
version: '3'

#-----------------------------------------------------------------------------------------
# ENVIRONMENT VARIABLES CONFIGURATION
# ----------------------------------
# - These variables are used to configure the environment for the task.
# - It's set while calling the task. E.g.: ENV=master task <task_name>
# - Remember to generate the .env.<env>.aws or .env.<env>.terraform previously.
#-----------------------------------------------------------------------------------------
env:
    TARGET_ENVIRONMENT: '{{.ENV}}'

dotenv: ['.env.{{.TARGET_ENVIRONMENT}}.aws', '.env.{{.TARGET_ENVIRONMENT}}.terraform']

includes:
    common:
        taskfile: ./DevEx/taskfile/Taskfile.common.yml

    devex:
        taskfile: ./DevEx/taskfile/Taskfile.devex.yml


  #-----------------------------------------------------------------------------------------
  # TERRAFORM/TERRAGRUNT MODULES
  # ----------------------------------
  # - These are specific IAC modules, either in Terragrunt o terraform that will be executed.
  # - Normally, these modules have their own TaskFile.yml in the folder infrastructure/terraform
  #-----------------------------------------------------------------------------------------
    module:
        taskfile: ./module/TaskFile.yml
        dir: ./module

    example-basic:
        taskfile: ./examples/basic/TaskFile.yml
        dir: ./examples/basic

tasks:
    default:
        cmds:
            - task: common:default

    pre-commit-init:
        desc: Initialize and install required hooks
        cmds:
            - task: common:hooks-install

    pre-commit:
        desc: Run all the pre-configured pre-commit hooks.
        cmds:
            - task: common:hooks

    gen-env-aws:
        desc: Generate an .env.<env>.aws file for a given environment
        cmds:
            - task: devex:gen-env-aws

    module-init:
        desc: Run Terraform Init on module's source code.
        cmds:
            - task: module:init

    module-ci:
        desc: Run common terraform tasks on module's folder.
        cmds:
            - task: module:docs
            - task: module:ci

    example-basic-init:
        desc: Run Terraform Init on module's example recipe source code.
        cmds:
            - task: example-basic:init

    example-basic-plan:
        desc: Run Terraform Plan on module's example recipe source code.
        cmds:
            - task: example-basic:plan

    example-basic-ci:
        desc: Run Set of checks, fmt and linting operations over the example's module.
        cmds:
            - task: example-basic:ci
            - task: example-basic:docs
