---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ AWS IAM Policy attacher
    ## Description
    {{ .Header }}
    This module is used to attach an IAM policy to a role or user. The current capabilities that are supported are:
    - Attach a policy to a role
    - Attach a policy to a user
    - Attach a policy to a group

    For more information about this specific resource, please refer to the [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html).

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/iam-policy-attacher/basic/main.tf" }}
    ```

    An example of passing a more complex set of functions to this role.
    ```hcl
    {{ include "../../examples/iam-policy-attacher/basic/config/fixtures.tfvars" }}
    ```
    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
