---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ AWS IAM Policy
    ## Description
    {{ .Header }}
    This module creates en AWS IAM Policy, with the following capabilities:
    - Create a Policy
    - Specify the policy document
    For more information about this AWS configuration, please refer to its official documentation: [AWS IAM Policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy)
    In terms of terraform, please query its official terraform-registry documentation for more information: [Terraform AWS IAM Policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy)

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/iam-policy/basic/main.tf" }}
    ```

    An example of passing a more complex set of functions to this role.
    ```hcl
    {{ include "../../examples/iam-policy/basic/config/fixtures.tfvars" }}
    ```

    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
