---
version: '3'

vars:
    working_dir: '{{default "." .tf_working_directory}}'


includes:
    common:
        taskfile: ./../../DevEx/taskfile/TaskFile.common.yml

    tf:
        taskfile: ./../../DevEx/taskfile/TaskFile.terraform.yml

tasks:
    clean:
        desc: Clean all the .terraform directories
        cmds:
            - task: common:clean

    init:
        deps: [clean]
        cmds:
            - task: tf:init
              vars: {TF_WORKING_DIR: '{{.working_dir}}'}

    plan:
        deps: [clean]
        cmds:
            - task: tf:plan
              vars: {TF_WORKING_DIR: '{{.working_dir}}'}

    apply:
        deps: [clean]
        cmds:
            - task: tf:apply
              vars: {TF_WORKING_DIR: '{{.working_dir}}'}


    destroy:
        deps: [clean]
        cmds:
            - task: tf:destroy
              vars: {TF_WORKING_DIR: '{{.working_dir}}'}

    ci:
        cmds:
            - task: tf:fmt-fix
#            - task: tf:validate
#            - task: tf:lint
            - task: tf:docs

    docs:
        deps: [clean]
        cmds:
            - task: tf:docs
