---
name: Run pre-commit

on:
    push:
        branches:
            - '*'
    pull_request:
        types: [opened, edited, synchronize]

env:
    PRE_COMMIT_CONFIG: ./.github/pre-commit-config-in-automation.yaml

jobs:
    run-all-hooks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - uses: terraform-linters/setup-tflint@v2
              name: Setup TFLint
              with:
                  tflint_version: v0.44.0
            - name: Install TfLInt and NodeJS
              run: |
                  npm install -g markdown-link-check
            - uses: golangci/golangci-lint-action@v3
            - uses: pre-commit/action@v3.0.0
              with:
                  pre-commit.config: ${{ env.PRE_COMMIT_CONFIG }}
