---
name: Terratest

on:
    pull_request:
        types: [opened, edited, synchronize]

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: tests/unit/basic
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                  go-version: 1.19
            - run: |
                  go test -v -count=1 -timeout 30m -parallel 128 -run ./...


    integration-tests:
        runs-on: ubuntu-latest
        needs: unit-tests
        defaults:
            run:
                working-directory: tests/integration/basic
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                  go-version: 1.19
            - run: |
                  go test -v -count=1 -timeout 30m -parallel 128 -run ./...
